"""add gift card

Revision ID: 04c5372c7f54
Revises: d77ea8e4ac1a
Create Date: 2018-02-08 01:03:47.961345

"""

# revision identifiers, used by Alembic.
revision = '04c5372c7f54'
down_revision = 'd77ea8e4ac1a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gift_card_code', sa.String(length=64), nullable=True),
    sa.Column('assigned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('twitter_user_metadata', sa.Column('gift_card_code', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_metadata', 'gift_card_code')
    op.drop_table('gift_cards')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gift_card_code', sa.String(length=64), nullable=True),
    sa.Column('assigned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('twitter_user_metadata', sa.Column('gift_card_code', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_metadata', 'gift_card_code')
    op.drop_table('gift_cards')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gift_card_code', sa.String(length=64), nullable=True),
    sa.Column('assigned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('twitter_user_metadata', sa.Column('gift_card_code', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_metadata', 'gift_card_code')
    op.drop_table('gift_cards')
    # ### end Alembic commands ###

