"""Rename record_created_at for clarity

Revision ID: 067975addada
Revises: 8cdbfc9dc6d3
Create Date: 2017-12-18 00:36:33.495802

"""

# revision identifiers, used by Alembic.
revision = '067975addada'
down_revision = '8cdbfc9dc6d3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_users', sa.Column('record_created_at', sa.DateTime(), nullable=True))
    op.drop_column('twitter_users', 'account_created_at')
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_users', sa.Column('account_created_at', mysql.DATETIME(), nullable=True))
    op.drop_column('twitter_users', 'record_created_at')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_users', sa.Column('record_created_at', sa.DateTime(), nullable=True))
    op.drop_column('twitter_users', 'account_created_at')
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_users', sa.Column('account_created_at', mysql.DATETIME(), nullable=True))
    op.drop_column('twitter_users', 'record_created_at')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_users', sa.Column('record_created_at', sa.DateTime(), nullable=True))
    op.drop_column('twitter_users', 'account_created_at')
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_users', sa.Column('account_created_at', mysql.DATETIME(), nullable=True))
    op.drop_column('twitter_users', 'record_created_at')
    # ### end Alembic commands ###

