"""add twitter user table

Revision ID: 0f4753eda07e
Revises: 
Create Date: 2017-11-29 18:26:41.692150

"""

# revision identifiers, used by Alembic.
revision = '0f4753eda07e'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('screen_name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('account_created_at', sa.DateTime(), nullable=True),
    sa.Column('lang', sa.String(length=32), nullable=True),
    sa.Column('user_state', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_users_screen_name'), 'twitter_users', ['screen_name'], unique=False)
    ### end Alembic commands ###


def downgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_users_screen_name'), table_name='twitter_users')
    op.drop_table('twitter_users')
    ### end Alembic commands ###


def upgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('screen_name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('account_created_at', sa.DateTime(), nullable=True),
    sa.Column('lang', sa.String(length=32), nullable=True),
    sa.Column('user_state', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_users_screen_name'), 'twitter_users', ['screen_name'], unique=False)
    ### end Alembic commands ###


def downgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_users_screen_name'), table_name='twitter_users')
    op.drop_table('twitter_users')
    ### end Alembic commands ###


def upgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('screen_name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('account_created_at', sa.DateTime(), nullable=True),
    sa.Column('lang', sa.String(length=32), nullable=True),
    sa.Column('user_state', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_users_screen_name'), 'twitter_users', ['screen_name'], unique=False)
    ### end Alembic commands ###


def downgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_users_screen_name'), table_name='twitter_users')
    op.drop_table('twitter_users')
    ### end Alembic commands ###

