"""modify db for debriefing

Revision ID: 266fc2005daa
Revises: 428ccb03765b
Create Date: 2019-03-30 22:22:50.438093

"""

# revision identifiers, used by Alembic.
revision = '266fc2005daa'
down_revision = '428ccb03765b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_randomizations_stratum', table_name='randomizations')
    op.drop_table('randomizations')
    op.add_column('twitter_user_eligibility', sa.Column('study_data_json', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_eligibility', 'study_data_json')
    op.create_table('randomizations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('randomization_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('stratum', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('block_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('block_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('treatment', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('assigned', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_randomizations_stratum', 'randomizations', ['stratum'], unique=False)
    # ### end Alembic commands ###



def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_randomizations_stratum', table_name='randomizations')
    op.drop_table('randomizations')
    op.add_column('twitter_user_eligibility', sa.Column('study_data_json', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_eligibility', 'study_data_json')
    op.create_table('randomizations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('randomization_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('stratum', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('block_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('block_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('treatment', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('assigned', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_randomizations_stratum', 'randomizations', ['stratum'], unique=False)
    # ### end Alembic commands ###



def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_randomizations_stratum', table_name='randomizations')
    op.drop_table('randomizations')
    op.add_column('twitter_user_eligibility', sa.Column('study_data_json', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_eligibility', 'study_data_json')
    op.create_table('randomizations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('randomization_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('stratum', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('block_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('block_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('treatment', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('assigned', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_randomizations_stratum', 'randomizations', ['stratum'], unique=False)
    # ### end Alembic commands ###

