"""add extra_data to eligibility

Revision ID: 428ccb03765b
Revises: 4dab42e24d6f
Create Date: 2018-12-19 17:29:44.441463

"""

# revision identifiers, used by Alembic.
revision = '428ccb03765b'
down_revision = '4dab42e24d6f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_eligibility', sa.Column('extra_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_eligibility', 'extra_data')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_eligibility', sa.Column('extra_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_eligibility', 'extra_data')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_eligibility', sa.Column('extra_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_eligibility', 'extra_data')
    # ### end Alembic commands ###

