"""add tweet body to tweet attempt

Revision ID: 4302608638bc
Revises: 474e96e30c5c
Create Date: 2018-03-29 18:03:53.874613

"""

# revision identifiers, used by Alembic.
revision = '4302608638bc'
down_revision = '474e96e30c5c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_recruitment_tweet_attempt', sa.Column('tweet_body', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_recruitment_tweet_attempt', 'tweet_body')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_recruitment_tweet_attempt', sa.Column('tweet_body', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_recruitment_tweet_attempt', 'tweet_body')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_recruitment_tweet_attempt', sa.Column('tweet_body', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_recruitment_tweet_attempt', 'tweet_body')
    # ### end Alembic commands ###

