"""add paypal send id to twitter user metadata

Revision ID: 47616107e240
Revises: d77ea8e4ac1a
Create Date: 2018-02-21 01:22:33.914961

"""

# revision identifiers, used by Alembic.
revision = '47616107e240'
down_revision = 'd77ea8e4ac1a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_metadata', sa.Column('paypal_sender_batch_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_metadata', 'paypal_sender_batch_id')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_metadata', sa.Column('paypal_sender_batch_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_metadata', 'paypal_sender_batch_id')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_metadata', sa.Column('paypal_sender_batch_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_metadata', 'paypal_sender_batch_id')
    # ### end Alembic commands ###

