"""Added extra_data to recruit attempt

Revision ID: 4dab42e24d6f
Revises: 4f53ec506661
Create Date: 2018-07-23 13:47:38.875696

"""

# revision identifiers, used by Alembic.
revision = '4dab42e24d6f'
down_revision = '4f53ec506661'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_recruitment_tweet_attempt', sa.Column('extra_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_recruitment_tweet_attempt', 'extra_data')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_recruitment_tweet_attempt', sa.Column('extra_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_recruitment_tweet_attempt', 'extra_data')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_recruitment_tweet_attempt', sa.Column('extra_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_recruitment_tweet_attempt', 'extra_data')
    # ### end Alembic commands ###

