"""add amount_dollars to tweet attempt

Revision ID: 5730636f9d23
Revises: 474e96e30c5c
Create Date: 2018-03-29 17:42:55.141809

"""

# revision identifiers, used by Alembic.
revision = '474e96e30c5c'
down_revision = '5c990792272f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_recruitment_tweet_attempt', sa.Column('amount_dollars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_recruitment_tweet_attempt', 'amount_dollars')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_recruitment_tweet_attempt', sa.Column('amount_dollars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_recruitment_tweet_attempt', 'amount_dollars')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_recruitment_tweet_attempt', sa.Column('amount_dollars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user_recruitment_tweet_attempt', 'amount_dollars')
    # ### end Alembic commands ###

