"""Add twitter user metadata

Revision ID: 7b8a9e7f8c9f
Revises: 0f4753eda07e
Create Date: 2017-12-04 00:57:44.289286

"""

# revision identifiers, used by Alembic.
revision = '7b8a9e7f8c9f'
down_revision = '0f4753eda07e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_user_metadata',
    sa.Column('twitter_user_id', sa.String(length=64), nullable=False),
    sa.Column('received_lumen_notice_at', sa.DateTime(), nullable=True),
    sa.Column('twitter_removed', sa.Boolean(), nullable=True),
    sa.Column('lumen_notice_id', sa.String(length=64), nullable=True),
    sa.Column('user_json', sa.LargeBinary(), nullable=True),
    sa.Column('assignment_json', sa.LargeBinary(), nullable=True),
    sa.Column('experiment_id', sa.String(length=64), nullable=True),
    sa.Column('initial_login_at', sa.DateTime(), nullable=True),
    sa.Column('completed_study_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('twitter_user_id')
    )
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_user_metadata')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_user_metadata',
    sa.Column('twitter_user_id', sa.String(length=64), nullable=False),
    sa.Column('received_lumen_notice_at', sa.DateTime(), nullable=True),
    sa.Column('twitter_removed', sa.Boolean(), nullable=True),
    sa.Column('lumen_notice_id', sa.String(length=64), nullable=True),
    sa.Column('user_json', sa.LargeBinary(), nullable=True),
    sa.Column('assignment_json', sa.LargeBinary(), nullable=True),
    sa.Column('experiment_id', sa.String(length=64), nullable=True),
    sa.Column('initial_login_at', sa.DateTime(), nullable=True),
    sa.Column('completed_study_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('twitter_user_id')
    )
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_user_metadata')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_user_metadata',
    sa.Column('twitter_user_id', sa.String(length=64), nullable=False),
    sa.Column('received_lumen_notice_at', sa.DateTime(), nullable=True),
    sa.Column('twitter_removed', sa.Boolean(), nullable=True),
    sa.Column('lumen_notice_id', sa.String(length=64), nullable=True),
    sa.Column('user_json', sa.LargeBinary(), nullable=True),
    sa.Column('assignment_json', sa.LargeBinary(), nullable=True),
    sa.Column('experiment_id', sa.String(length=64), nullable=True),
    sa.Column('initial_login_at', sa.DateTime(), nullable=True),
    sa.Column('completed_study_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('twitter_user_id')
    )
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_user_metadata')
    # ### end Alembic commands ###

