"""Rename tweet_removed for clarity

Revision ID: 8cdbfc9dc6d3
Revises: 29b5c90d0fc3
Create Date: 2017-12-17 18:26:28.774252

"""

# revision identifiers, used by Alembic.
revision = '8cdbfc9dc6d3'
down_revision = '29b5c90d0fc3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_metadata', sa.Column('tweet_removed', sa.Boolean(), nullable=True))
    op.drop_column('twitter_user_metadata', 'twitter_removed')
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_metadata', sa.Column('twitter_removed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('twitter_user_metadata', 'tweet_removed')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_metadata', sa.Column('tweet_removed', sa.Boolean(), nullable=True))
    op.drop_column('twitter_user_metadata', 'twitter_removed')
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_metadata', sa.Column('twitter_removed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('twitter_user_metadata', 'tweet_removed')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_metadata', sa.Column('tweet_removed', sa.Boolean(), nullable=True))
    op.drop_column('twitter_user_metadata', 'twitter_removed')
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user_metadata', sa.Column('twitter_removed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('twitter_user_metadata', 'tweet_removed')
    # ### end Alembic commands ###

