"""Add Twitter User Metadata Table

Revision ID: b82c166efe70
Revises: 0f4753eda07e
Create Date: 2017-12-03 02:35:30.597738

"""

# revision identifiers, used by Alembic.
revision = 'b82c166efe70'
down_revision = '0f4753eda07e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_users_metadata',
    sa.Column('twitter_user_id', mysql.INTEGER(display_width=64), autoincrement=False, nullable=False),
    sa.Column('received_lumen_notice_at', mysql.DATETIME(), nullable=True),
    sa.Column('twitter_removed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('lumen_notice_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_json', sa.BLOB(), nullable=True),
    sa.Column('assignment_json', sa.BLOB(), nullable=True),
    sa.Column('experiment_id', sa.String(length=64), autoincrement=False, nullable=True),
    sa.Column('initial_login_at', mysql.DATETIME(), nullable=True),
    sa.Column('completed_study_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('twitter_user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_users_metadata')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_users_metadata',
    sa.Column('twitter_user_id', mysql.INTEGER(display_width=64), autoincrement=False, nullable=False),
    sa.Column('received_lumen_notice_at', mysql.DATETIME(), nullable=True),
    sa.Column('twitter_removed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('lumen_notice_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_json', sa.BLOB(), nullable=True),
    sa.Column('assignment_json', sa.BLOB(), nullable=True),
    sa.Column('experiment_id', sa.String(length=64), autoincrement=False, nullable=True),
    sa.Column('initial_login_at', mysql.DATETIME(), nullable=True),
    sa.Column('completed_study_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('twitter_user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_users_metadata')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_users_metadata',
    sa.Column('twitter_user_id', mysql.INTEGER(display_width=64), autoincrement=False, nullable=False),
    sa.Column('received_lumen_notice_at', mysql.DATETIME(), nullable=True),
    sa.Column('twitter_removed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('lumen_notice_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_json', sa.BLOB(), nullable=True),
    sa.Column('assignment_json', sa.BLOB(), nullable=True),
    sa.Column('experiment_id', sa.String(length=64), autoincrement=False, nullable=True),
    sa.Column('initial_login_at', mysql.DATETIME(), nullable=True),
    sa.Column('completed_study_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('twitter_user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_users_metadata')
    # ### end Alembic commands ###

