"""add twitter user eligibility table

Revision ID: d77ea8e4ac1a
Revises: 0b6e7324eded
Create Date: 2017-12-21 20:58:48.210114

"""

# revision identifiers, used by Alembic.
revision = 'd77ea8e4ac1a'
down_revision = '0b6e7324eded'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_user_eligibility',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('twitter_user_message_attempt')
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_user_message_attempt',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('message_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('account_found', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('twitter_user_eligibility')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_user_eligibility',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('twitter_user_message_attempt')
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_user_message_attempt',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('message_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('account_found', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('twitter_user_eligibility')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_user_eligibility',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('twitter_user_message_attempt')
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_user_message_attempt',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('message_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('account_found', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('twitter_user_eligibility')
    # ### end Alembic commands ###

