"""add tweet attempt

Revision ID: fe4aaca93748
Revises: 47616107e240
Create Date: 2018-02-24 21:21:23.151271

"""

# revision identifiers, used by Alembic.
revision = 'fe4aaca93748'
down_revision = '47616107e240'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_user_recruitment_tweet_attempt',
    sa.Column('twitter_user_id', sa.String(length=64), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.Column('lang', sa.String(length=32), nullable=True),
    sa.Column('last_tweeted_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('twitter_user_id')
    )
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_user_recruitment_tweet_attempt')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_user_recruitment_tweet_attempt',
    sa.Column('twitter_user_id', sa.String(length=64), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.Column('lang', sa.String(length=32), nullable=True),
    sa.Column('last_tweeted_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('twitter_user_id')
    )
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_user_recruitment_tweet_attempt')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_user_recruitment_tweet_attempt',
    sa.Column('twitter_user_id', sa.String(length=64), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.Column('lang', sa.String(length=32), nullable=True),
    sa.Column('last_tweeted_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('twitter_user_id')
    )
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_user_recruitment_tweet_attempt')
    # ### end Alembic commands ###

